#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# Code available from: https://verilator.org
#
#*************************************************************************
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

import json
import re
from pathlib import Path

import vltest_bootstrap

test.scenarios('vlt')

out_filename = test.obj_dir + "/model-manifest.json"

test.compile(verilator_flags2=['--model-manifest-output', out_filename, '--stats'],
             verilator_make_gmake=False,
             make_top_shell=False,
             make_main=False)

with open(out_filename, 'r', encoding='utf8') as fh:
    manifest = json.load(fh)

if manifest['schema_version'] != 1:
    test.error('unexpected model manifest schema')
if manifest['surface'] != 'verilator_model_manifest_experimental':
    test.error('unexpected model manifest surface')
if manifest['model']['top'] != 't':
    test.error('unexpected model top')

fields = {field['field_id']: field for field in manifest['fields']}
if manifest['field_count'] != len(fields):
    test.error('incorrect model manifest field count')
for field_id, width, direction in (('rtl:t.clk', 1, 'INPUT'), ('rtl:t.data_i', 8, 'INPUT'),
                                   ('rtl:t.data_o', 8, 'OUTPUT'), ('rtl:t.__Vuser_q', 1, 'NONE'),
                                   ('rtl:t.state_q', 8, 'NONE'),
                                   ('rtl:status_if.done', 1, 'NONE')):
    field = fields.get(field_id)
    if field is None:
        test.error('missing model manifest field ' + field_id)
    elif field['width_bits'] != width or field['direction'] != direction:
        test.error('incorrect model manifest field ' + field_id)

if not any(field['origin'] == 'compiler_generated' for field in manifest['fields']):
    test.error('missing compiler-generated model field')
if manifest['limitations']['semantic_state_classification'] != 'not_provided':
    test.error('experimental manifest overclaims semantic state classification')
if any('byte_offset' in field['generated_binding'] for field in manifest['fields']):
    test.error('experimental manifest overclaims generated byte offsets')

headers = {}
for field in manifest['fields']:
    binding = field['generated_binding']
    container = binding['container']
    if container not in headers:
        header_path = Path(test.obj_dir) / (container + '.h')
        headers[container] = header_path.read_text(encoding='utf8')
    if not re.search(r'\b' + re.escape(binding['member']) + r'\b', headers[container]):
        test.error('generated binding is absent from header for ' + field['field_id'])

instances = {instance['instance_id']: instance for instance in manifest['instances']}
if manifest['instance_count'] != 2 or len(instances) != 2:
    test.error('incorrect model manifest instance count')
top_instance = instances.get('rtl_instance:t')
status_instance = instances.get('rtl_instance:t.status')
if top_instance is None or not top_instance['is_top']:
    test.error('missing top model manifest instance')
if status_instance is None:
    test.error('missing interface model manifest instance')
elif status_instance['parent_instance_id'] != 'rtl_instance:t':
    test.error('incorrect interface parent instance')
else:
    status_field = fields['rtl:status_if.done']
    if (status_instance['module_binding']['container']
            != status_field['generated_binding']['container']):
        test.error('interface instance does not bind its field container')
    syms_header = Path(test.obj_dir) / (
        status_instance['generated_binding']['container'] + '.h')
    if not re.search(
            r'\b' + re.escape(status_instance['generated_binding']['member']) + r'\b',
            syms_header.read_text(encoding='utf8')):
        test.error('generated interface instance binding is absent from symbol header')

if manifest['limitations']['generated_storage_instances'] != 'provided':
    test.error('model manifest does not declare generated storage instances')
if manifest['limitations']['semantic_instance_topology'] != 'not_provided':
    test.error('model manifest overclaims complete semantic instance topology')

test.file_grep(test.stats, r'Model manifest, Fields emitted\s+(\d+)', len(fields))
test.file_grep(test.stats, r'Model manifest, Instances emitted\s+(\d+)', 2)

test.passes()
