#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# Code available from: https://verilator.org
#
#*************************************************************************
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

import json
import re
from pathlib import Path

import vltest_bootstrap

test.scenarios('vlt')

out_filename = test.obj_dir + "/model-manifest.json"

test.compile(verilator_flags2=['--model-manifest-output', out_filename, '--stats'],
             verilator_make_gmake=False,
             make_top_shell=False,
             make_main=False)

with open(out_filename, 'r', encoding='utf8') as fh:
    manifest = json.load(fh)

if manifest['schema_version'] != 1:
    test.error('unexpected model manifest schema')
if manifest['surface'] != 'verilator_model_manifest_experimental':
    test.error('unexpected model manifest surface')
if manifest['model']['top'] != 't':
    test.error('unexpected model top')

coverage = manifest['coverage']
if coverage['status'] != 'not_present':
    test.error('non-covered model reports a coverage mapping')
if any(coverage[name] for name in ('storages', 'lowering_declarations',
                                    'semantic_observations', 'bindings',
                                    'physical_words', 'update_regions')):
    test.error('non-covered model reports coverage records')
if manifest['limitations']['coverage_mapping'] != 'not_present':
    test.error('non-covered model overclaims a coverage mapping')

fields = {field['field_id']: field for field in manifest['fields']}
if manifest['field_count'] != len(fields):
    test.error('incorrect model manifest field count')
for field_id, width, direction in (('rtl:t.clk', 1, 'INPUT'), ('rtl:t.data_i', 8, 'INPUT'),
                                   ('rtl:t.data_o', 8, 'OUTPUT'), ('rtl:t.__Vuser_q', 1, 'NONE'),
                                   ('rtl:t.state_q', 8, 'NONE'), ('rtl:status_if.done', 1,
                                                                  'NONE')):
    field = fields.get(field_id)
    if field is None:
        test.error('missing model manifest field ' + field_id)
    elif field['width_bits'] != width or field['direction'] != direction:
        test.error('incorrect model manifest field ' + field_id)

if not any(field['origin'] == 'compiler_generated' for field in manifest['fields']):
    test.error('missing compiler-generated model field')
if manifest['limitations']['semantic_state_classification'] != 'not_provided':
    test.error('experimental manifest overclaims semantic state classification')
if any('byte_offset' in field['generated_binding'] for field in manifest['fields']):
    test.error('experimental manifest overclaims generated byte offsets')

checkpoint = manifest['checkpoint_projection']
included_fields = [
    field for field in manifest['fields'] if field['checkpoint_membership']['status'] == 'included'
]
excluded_fields = [
    field for field in manifest['fields'] if field['checkpoint_membership']['status'] == 'excluded'
]
if checkpoint['status'] != 'field_membership_only':
    test.error('model manifest overclaims a complete checkpoint projection')
if checkpoint['included_definition_field_count'] != len(included_fields):
    test.error('incorrect included checkpoint field count')
if checkpoint['excluded_definition_field_count'] != len(excluded_fields):
    test.error('incorrect excluded checkpoint field count')
if len(included_fields) + len(excluded_fields) != len(fields):
    test.error('checkpoint membership does not classify every emitted field')
if fields['rtl:t.state_q']['checkpoint_membership'] != {
        'status': 'included',
        'authority': 'verilator_savable_field_selection',
        'reason': 'serialized_field'
}:
    test.error('incorrect checkpoint membership for state_q')
if checkpoint['runtime_state'] != 'not_provided' or checkpoint['packing'] != 'not_provided':
    test.error('model manifest overclaims checkpoint runtime state or packing')

headers = {}
for field in manifest['fields']:
    binding = field['generated_binding']
    container = binding['container']
    if container not in headers:
        header_path = Path(test.obj_dir) / (container + '.h')
        headers[container] = header_path.read_text(encoding='utf8')
    if not re.search(r'\b' + re.escape(binding['member']) + r'\b', headers[container]):
        test.error('generated binding is absent from header for ' + field['field_id'])

instances = {instance['instance_id']: instance for instance in manifest['instances']}
if manifest['instance_count'] != 2 or len(instances) != 2:
    test.error('incorrect model manifest instance count')
top_instance = instances.get('rtl_instance:t')
status_instance = instances.get('rtl_instance:t.status')
if top_instance is None or not top_instance['is_top']:
    test.error('missing top model manifest instance')
if status_instance is None:
    test.error('missing interface model manifest instance')
elif status_instance['parent_instance_id'] != 'rtl_instance:t':
    test.error('incorrect interface parent instance')
else:
    status_field = fields['rtl:status_if.done']
    if (status_instance['module_binding']['container']
            != status_field['generated_binding']['container']):
        test.error('interface instance does not bind its field container')
    syms_header = Path(test.obj_dir) / (status_instance['generated_binding']['container'] + '.h')
    if not re.search(r'\b' + re.escape(status_instance['generated_binding']['member']) + r'\b',
                     syms_header.read_text(encoding='utf8')):
        test.error('generated interface instance binding is absent from symbol header')

if manifest['limitations']['generated_storage_instances'] != 'provided':
    test.error('model manifest does not declare generated storage instances')
if manifest['limitations']['semantic_instance_topology'] != 'not_provided':
    test.error('model manifest overclaims complete semantic instance topology')
if manifest['limitations']['checkpoint_field_membership'] != 'provided':
    test.error('model manifest does not declare checkpoint field membership')
if manifest['limitations']['pointer_free_checkpoint'] != 'not_provided':
    test.error('model manifest overclaims a pointer-free checkpoint')

test.file_grep(test.stats, r'Model manifest, Fields emitted\s+(\d+)', len(fields))
test.file_grep(test.stats, r'Model manifest, Instances emitted\s+(\d+)', 2)
test.file_grep(test.stats, r'Model manifest, Checkpoint fields included\s+(\d+)',
               len(included_fields))
test.file_grep(test.stats, r'Model manifest, Coverage observations emitted\s+(\d+)', 0)
test.file_grep(test.stats, r'Model manifest, Coverage physical words emitted\s+(\d+)', 0)

test.passes()
