#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# Code available from: https://verilator.org
#
#*************************************************************************
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Wilson Snyder
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0

import json
import re
from pathlib import Path

import vltest_bootstrap

test.scenarios('vlt')

out_filename = test.obj_dir + "/model-manifest.json"

test.compile(verilator_flags2=['--model-manifest-output', out_filename],
             verilator_make_gmake=False,
             make_top_shell=False,
             make_main=False)

with open(out_filename, 'r', encoding='utf8') as fh:
    manifest = json.load(fh)

if manifest['schema_version'] != 1:
    test.error('unexpected model manifest schema')
if manifest['surface'] != 'verilator_model_manifest_experimental':
    test.error('unexpected model manifest surface')
if manifest['model']['top'] != 't':
    test.error('unexpected model top')

fields = {field['field_id']: field for field in manifest['fields']}
if manifest['field_count'] != len(fields):
    test.error('incorrect model manifest field count')
for field_id, width, direction in (
        ('rtl:t.clk', 1, 'INPUT'),
        ('rtl:t.data_i', 8, 'INPUT'),
        ('rtl:t.data_o', 8, 'OUTPUT'),
        ('rtl:t.state_q', 8, 'NONE')):
    field = fields.get(field_id)
    if field is None:
        test.error('missing model manifest field ' + field_id)
    elif field['width_bits'] != width or field['direction'] != direction:
        test.error('incorrect model manifest field ' + field_id)

if not any(field['origin'] == 'compiler_generated' for field in manifest['fields']):
    test.error('missing compiler-generated model field')
if manifest['limitations']['semantic_state_classification'] != 'not_provided':
    test.error('experimental manifest overclaims semantic state classification')
if any('byte_offset' in field['generated_binding'] for field in manifest['fields']):
    test.error('experimental manifest overclaims generated byte offsets')

headers = {}
for field in manifest['fields']:
    binding = field['generated_binding']
    container = binding['container']
    if container not in headers:
        header_path = Path(test.obj_dir) / (container + '.h')
        headers[container] = header_path.read_text(encoding='utf8')
    if not re.search(r'\b' + re.escape(binding['member']) + r'\b', headers[container]):
        test.error('generated binding is absent from header for ' + field['field_id'])

test.passes()
