// DESCRIPTION: Verilator: Sim-Accel CUDA File Writer
//
// Code available from: https://verilator.org
//
// This program is free software; you can redistribute it and/or modify it
// under the terms of either the GNU Lesser General Public License Version 3
// or the Perl Artistic License Version 2.0.
// SPDX-FileCopyrightText: 2026-2026 Wilson Snyder
// SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
//
//=============================================================================

#include "V3SimAccelBackendCudaWriter.h"

#include "V3Error.h"
#include "V3SimAccelBackendCudaExprEmitter.h"

#include <fstream>
#include <sstream>
#include <unordered_set>

namespace {

uint32_t simAccelMaskValue(int width) {
    if (width <= 0) return 0U;
    if (width >= 32) return 0xffffffffU;
    return static_cast<uint32_t>((1ULL << width) - 1ULL);
}

string simAccelMaskLiteral(int width) {
    std::ostringstream os;
    os << "0x" << std::hex << std::nouppercase << simAccelMaskValue(width) << "u";
    return os.str();
}

string simAccelEscapeCString(const string& in) {
    string out;
    out.reserve(in.size() + 8);
    for (char ch : in) {
        if (ch == '\\' || ch == '"') out += '\\';
        out += ch;
    }
    return out;
}

struct EmittedAssign final {
    size_t m_lhsIdx = 0;
    string m_lhsName;
    string m_expr;
    std::vector<size_t> m_rhsIdxs;
};

}  // namespace

size_t V3SimAccelBackendCudaWriter::write(const string& filename,
                                          const V3SimAccelProgram& program) {
    std::ofstream of{filename};
    if (!of.is_open()) v3fatal("Cannot open output file: " + filename);  // LCOV_EXCL_LINE

    of << "// Generated by Verilator --sim-accel-only\n"
       << "// Supported node subset: ASSIGNW + bool/arith/select/shift/concat (+ casts/extends)\n"
       << "#include <stdint.h>\n\n";

    of << "extern \"C\" __global__ void sim_accel_eval_assignw_u32(const uint32_t* state_in,\n"
       << "                                                  uint32_t* state_out,\n"
       << "                                                  uint32_t nstates) {\n"
       << "    const uint32_t tid = blockIdx.x * blockDim.x + threadIdx.x;\n"
       << "    if (tid >= nstates) return;\n";

    const V3SimAccelBackendCudaExprEmitter emitter{program};
    std::unordered_set<string> emittedAssignKeys;
    std::vector<EmittedAssign> emittedAssigns;
    std::unordered_set<size_t> writtenVarIdxs;
    std::unordered_set<size_t> readVarIdxs;

    for (const V3SimAccelProgram::Assign& assign : program.m_assigns) {
        const string expr = emitter.emit(assign.m_exprIdx);
        if (expr == ("v_" + cvtToStr(assign.m_lhsIdx))) continue;
        const string key = cvtToStr(assign.m_lhsIdx) + "|" + expr;
        if (!emittedAssignKeys.emplace(key).second) continue;

        EmittedAssign rec;
        rec.m_lhsIdx = assign.m_lhsIdx;
        rec.m_lhsName = assign.m_lhsName;
        rec.m_expr = expr;
        rec.m_rhsIdxs = assign.m_rhsIdxs;
        for (const size_t rhsIdx : rec.m_rhsIdxs) readVarIdxs.emplace(rhsIdx);
        writtenVarIdxs.emplace(rec.m_lhsIdx);
        emittedAssigns.push_back(std::move(rec));
    }

    for (size_t i = 0; i < program.m_vars.size(); ++i) {
        const V3SimAccelProgram::Var& var = program.m_vars.at(i);
        if (readVarIdxs.find(i) != readVarIdxs.end()) {
            of << "    uint32_t v_" << i << " = state_in[" << i << "U * nstates + tid] & "
               << simAccelMaskLiteral(var.m_width) << ";  // " << var.m_name << "\n";
        } else if (writtenVarIdxs.find(i) != writtenVarIdxs.end()) {
            of << "    uint32_t v_" << i << " = 0u;  // " << var.m_name << " (write-only)\n";
        }
    }
    of << "\n";

    for (const EmittedAssign& assign : emittedAssigns) {
        of << "    v_" << assign.m_lhsIdx << " = " << assign.m_expr << ";  // "
           << assign.m_lhsName << "\n";
    }
    of << "\n";

    for (size_t i = 0; i < program.m_vars.size(); ++i) {
        const V3SimAccelProgram::Var& var = program.m_vars.at(i);
        if (writtenVarIdxs.find(i) != writtenVarIdxs.end()) {
            of << "    state_out[" << i << "U * nstates + tid] = v_" << i << " & "
               << simAccelMaskLiteral(var.m_width) << ";\n";
        } else {
            of << "#ifndef SIM_ACCEL_PARTIAL_WRITE\n";
            of << "    state_out[" << i << "U * nstates + tid] = state_in[" << i
               << "U * nstates + tid] & " << simAccelMaskLiteral(var.m_width) << ";\n";
            of << "#endif\n";
        }
    }
    of << "}\n\n";

    of << "extern \"C\" __host__ uint32_t sim_accel_eval_var_count() {\n"
       << "    return " << program.m_vars.size() << "U;\n"
       << "}\n\n";

    of << "extern \"C\" __host__ const char* sim_accel_eval_var_name(uint32_t index) {\n"
       << "    switch (index) {\n";
    for (size_t i = 0; i < program.m_vars.size(); ++i) {
        of << "    case " << i << "U: return \""
           << simAccelEscapeCString(program.m_vars.at(i).m_name) << "\";\n";
    }
    of << "    default: return \"\";\n"
       << "    }\n"
       << "}\n";
    of.close();

    const string metaFilename = filename + ".vars.tsv";
    std::ofstream met{metaFilename};
    if (met.is_open()) {
        met << "index\tname\thierarchy\tdirection\tis_primary_io\twidth\tis_activator\n";
        for (size_t i = 0; i < program.m_vars.size(); ++i) {
            const V3SimAccelProgram::Var& var = program.m_vars.at(i);
            met << i << '\t' << var.m_name << '\t' << var.m_hierarchy << '\t'
                << var.m_direction << '\t' << (var.m_isPrimaryIo ? "1" : "0") << '\t'
                << var.m_width << '\t' << (var.m_isActivator ? "1" : "0") << '\n';
        }
    }

    const string depsFilename = filename + ".deps.tsv";
    std::ofstream dep{depsFilename};
    if (dep.is_open()) {
        dep << "lhs_idx\trhs_idx_list\n";
        for (const EmittedAssign& assign : emittedAssigns) {
            dep << assign.m_lhsIdx << "\t";
            bool first = true;
            for (const size_t rhsIdx : assign.m_rhsIdxs) {
                if (!first) dep << ",";
                dep << rhsIdx;
                first = false;
            }
            dep << "\n";
        }
    }

    return emittedAssigns.size();
}
